#!/usr/bin/env bash
# Compile macOS .app bundles that wrap bin/start.sh, bin/stop.sh, bin/backup.sh
# so they can be double-clicked or pinned to the Dock.
#
# Usage:
#   mac/build-apps.sh              # installs into ~/Applications (default)
#   mac/build-apps.sh /Applications  # system-wide (may need sudo)
#
# Re-run after moving the project — the bundles encode an absolute path.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
DEST_DIR="${1:-$HOME/Applications}"
mkdir -p "$DEST_DIR"

c_grn='\033[0;32m'; c_rst='\033[0m'
say() { printf "${c_grn}==>${c_rst} %s\n" "$*"; }

build_app() {
  local label="$1"
  local script_name="$2"
  local app_path="${DEST_DIR}/${label}.app"
  local tmp
  tmp="$(mktemp -t cc-build-app)"
  mv "$tmp" "${tmp}.applescript"
  tmp="${tmp}.applescript"
  cat > "$tmp" <<EOF
-- Auto-generated by mac/build-apps.sh — do not edit in place.
-- Regenerate by running: mac/build-apps.sh
on run
  set scriptPath to "${PROJECT_DIR}/bin/${script_name}"
  tell application "Terminal"
    activate
    do script "clear; " & quoted form of scriptPath
  end tell
end run
EOF
  rm -rf "$app_path"
  osacompile -o "$app_path" "$tmp"
  rm "$tmp"
  say "Built ${app_path}"
}

build_app "Compliance Compass — Start"  "start.sh"
build_app "Compliance Compass — Stop"   "stop.sh"
build_app "Compliance Compass — Backup" "backup.sh"

cat <<EOF

Done. The three apps live in: ${DEST_DIR}

To pin to the Dock: drag any of them onto the Dock from Finder.
The first time you launch each one, macOS may ask you to confirm running
it (right-click → Open if so). It will also ask Terminal for permission
to control your Mac on first run — that's normal for AppleScript apps.
EOF
