// Generates supabase/seed.sql from public/seed/controls.csv (Secureframe export).
//
// Behavior:
//   - Inserts framework rows (Secureframe Baseline, SOC 2, CIS IG1, plus
//     placeholder rows for HIPAA, ISO 27001, NIST CSF).
//   - Inserts every Secureframe control under the "secureframe" framework,
//     preserving parent/child via a deterministic UUID derived from the
//     control_ref so parent_control_id can be resolved without lookups.
//   - For each unique SOC 2 / CIS IG1 reference appearing in the CSV, inserts
//     a placeholder control row under the corresponding framework.
//   - Generates crosswalk rows: secureframe → SOC 2 (direct/inherited/effective)
//     and secureframe → CIS IG1 (related).
//
// Run:  node scripts/generate-seed.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import Papa from 'papaparse';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const CSV_PATH = path.join(ROOT, 'public/seed/controls.csv');
const OUT_PATH = path.join(ROOT, 'supabase/seed.sql');

// Stable v5-style UUID derived from a string. Keeps seed deterministic across
// resets so foreign-key references resolve without separate lookups.
function uuidFor(namespace, value) {
  const h = createHash('sha1').update(`${namespace}::${value}`).digest('hex');
  return [
    h.substring(0, 8),
    h.substring(8, 12),
    '5' + h.substring(13, 16),
    ((parseInt(h.substring(16, 18), 16) & 0x3f) | 0x80).toString(16).padStart(2, '0') + h.substring(18, 20),
    h.substring(20, 32),
  ].join('-');
}

function sqlString(v) {
  if (v === null || v === undefined || v === '') return 'null';
  return `'${String(v).replace(/'/g, "''")}'`;
}

const FRAMEWORKS = [
  { slug: 'secureframe',   name: 'Secureframe Baseline',  version: null,           description: 'Operative internal control catalog (Secureframe-derived).' },
  { slug: 'soc2',          name: 'SOC 2',                 version: 'Type II',      description: 'AICPA Trust Services Criteria.' },
  { slug: 'cis-ig1',       name: 'CIS Controls IG1',      version: 'v8',           description: 'Center for Internet Security Implementation Group 1.' },
  { slug: 'hipaa',         name: 'HIPAA Security Rule',   version: null,           description: '45 CFR §164 Subpart C.' },
  { slug: 'iso-27001',     name: 'ISO/IEC 27001',         version: '2022',         description: 'Information security management system.' },
  { slug: 'nist-csf',      name: 'NIST Cybersecurity Framework', version: '2.0',   description: 'NIST CSF 2.0 functions and categories.' },
];

function frameworkUuid(slug) {
  return uuidFor('framework', slug);
}
function controlUuid(frameworkSlug, controlRef) {
  return uuidFor('control', `${frameworkSlug}::${controlRef}`);
}

const csv = readFileSync(CSV_PATH, 'utf8');
const parsed = Papa.parse(csv, { header: true, skipEmptyLines: true });
if (parsed.errors?.length) {
  console.error('CSV parse errors:', parsed.errors);
  process.exit(1);
}

const rows = parsed.data.filter((r) => r['Control Code']);
const allCodes = new Set(rows.map((r) => r['Control Code'].trim()));

// Collect unique foreign-framework references
const soc2Refs = new Set();
const cisRefs = new Set();
function splitRefs(s) {
  return (s || '')
    .split(/[,;\s]+/)
    .map((x) => x.trim())
    .filter(Boolean);
}
for (const r of rows) {
  for (const ref of splitRefs(r['SOC 2 Direct Mapping']))    soc2Refs.add(ref);
  for (const ref of splitRefs(r['SOC 2 Inherited Mapping'])) soc2Refs.add(ref);
  for (const ref of splitRefs(r['SOC 2 Effective Mapping'])) soc2Refs.add(ref);
  for (const ref of splitRefs(r['CIS IG1 Mapping']))         cisRefs.add(ref);
}

// -------------------------------------------------------------------------
// Build SQL
// -------------------------------------------------------------------------
const out = [];
out.push('-- =========================================================================');
out.push('-- Auto-generated by scripts/generate-seed.mjs from public/seed/controls.csv');
out.push('-- Edit the CSV (or the script), not this file.');
out.push('-- =========================================================================');
out.push('');
out.push('begin;');
out.push('');

// Frameworks
out.push('-- Frameworks');
for (const f of FRAMEWORKS) {
  out.push(
    `insert into public.frameworks (id, slug, name, version, description) values (` +
    `${sqlString(frameworkUuid(f.slug))}::uuid, ${sqlString(f.slug)}, ${sqlString(f.name)}, ${sqlString(f.version)}, ${sqlString(f.description)})` +
    ` on conflict (slug) do update set name = excluded.name, version = excluded.version, description = excluded.description;`
  );
}
out.push('');

// Foreign framework placeholder controls (SOC 2, CIS IG1)
out.push('-- SOC 2 reference controls (titles inferred from code; refine later)');
for (const ref of [...soc2Refs].sort()) {
  out.push(
    `insert into public.controls (id, framework_id, control_ref, title, control_type, source) values (` +
    `${sqlString(controlUuid('soc2', ref))}::uuid, ${sqlString(frameworkUuid('soc2'))}::uuid, ` +
    `${sqlString(ref)}, ${sqlString(`SOC 2 ${ref}`)}, 'standalone'::public.control_type, 'Inferred from Secureframe crosswalk')` +
    ` on conflict (framework_id, control_ref) do nothing;`
  );
}
out.push('');

out.push('-- CIS IG1 reference controls');
for (const ref of [...cisRefs].sort()) {
  out.push(
    `insert into public.controls (id, framework_id, control_ref, title, control_type, source) values (` +
    `${sqlString(controlUuid('cis-ig1', ref))}::uuid, ${sqlString(frameworkUuid('cis-ig1'))}::uuid, ` +
    `${sqlString(ref)}, ${sqlString(`CIS IG1 ${ref}`)}, 'standalone'::public.control_type, 'Inferred from Secureframe crosswalk')` +
    ` on conflict (framework_id, control_ref) do nothing;`
  );
}
out.push('');

// Secureframe controls — two passes so child rows can reference parent rows
const secureframeId = frameworkUuid('secureframe');

out.push('-- Secureframe operative controls (parents first, then children)');
const orderedRows = [...rows].sort((a, b) => {
  const aHasParent = !!(a['Parent Control Code'] && a['Parent Control Code'].trim());
  const bHasParent = !!(b['Parent Control Code'] && b['Parent Control Code'].trim());
  if (aHasParent === bHasParent) return a['Control Code'].localeCompare(b['Control Code']);
  return aHasParent ? 1 : -1;
});

for (const r of orderedRows) {
  const code   = r['Control Code'].trim();
  let parent   = (r['Parent Control Code'] || '').trim();
  // Drop parent references that don't exist as their own row in the CSV.
  if (parent && !allCodes.has(parent)) parent = '';
  const ctype  = parent ? 'child' : ((r['Control Type'] || '').toLowerCase().includes('parent') ? 'parent' : 'standalone');
  const id        = controlUuid('secureframe', code);
  const parentId  = parent ? controlUuid('secureframe', parent) : null;

  out.push(
    `insert into public.controls (id, framework_id, parent_control_id, control_ref, title, description, domain, control_type, recommendation_template, evidence_examples, evidence_keywords, source) values (` +
    `${sqlString(id)}::uuid, ${sqlString(secureframeId)}::uuid, ` +
    `${parentId ? sqlString(parentId) + '::uuid' : 'null'}, ` +
    `${sqlString(code)}, ${sqlString(code)}, ${sqlString(r['Description'])}, ${sqlString(r['Domain'])}, ` +
    `${sqlString(ctype)}::public.control_type, ` +
    `${sqlString(r['Recommendation Template'])}, ${sqlString(r['Suggested Evidence Examples'])}, ${sqlString(r['Evidence Keywords'])}, ` +
    `${sqlString(r['Source'])})` +
    ` on conflict (framework_id, control_ref) do update set ` +
    `parent_control_id = excluded.parent_control_id, ` +
    `description = excluded.description, ` +
    `domain = excluded.domain, ` +
    `control_type = excluded.control_type, ` +
    `recommendation_template = excluded.recommendation_template, ` +
    `evidence_examples = excluded.evidence_examples, ` +
    `evidence_keywords = excluded.evidence_keywords, ` +
    `source = excluded.source;`
  );
}
out.push('');

// Crosswalks: Secureframe -> SOC 2 / CIS IG1
out.push('-- Crosswalks: Secureframe -> SOC 2');
const seen = new Set();
function addCrosswalk(sourceId, targetId, mappingType) {
  const key = `${sourceId}|${targetId}|${mappingType}`;
  if (seen.has(key)) return;
  seen.add(key);
  out.push(
    `insert into public.crosswalks (source_control_id, target_control_id, mapping_type) values (` +
    `${sqlString(sourceId)}::uuid, ${sqlString(targetId)}::uuid, ${sqlString(mappingType)}::public.crosswalk_mapping_type)` +
    ` on conflict (source_control_id, target_control_id, mapping_type) do nothing;`
  );
}

for (const r of rows) {
  const code = r['Control Code'].trim();
  const sourceId = controlUuid('secureframe', code);

  for (const ref of splitRefs(r['SOC 2 Direct Mapping']))    addCrosswalk(sourceId, controlUuid('soc2', ref), 'direct');
  for (const ref of splitRefs(r['SOC 2 Inherited Mapping'])) addCrosswalk(sourceId, controlUuid('soc2', ref), 'inherited');
  for (const ref of splitRefs(r['SOC 2 Effective Mapping'])) addCrosswalk(sourceId, controlUuid('soc2', ref), 'effective');
  for (const ref of splitRefs(r['CIS IG1 Mapping']))         addCrosswalk(sourceId, controlUuid('cis-ig1', ref), 'related');
}
out.push('');

out.push('commit;');
out.push('');

writeFileSync(OUT_PATH, out.join('\n'));
console.log(`Wrote ${OUT_PATH}`);
console.log(`  ${FRAMEWORKS.length} frameworks`);
console.log(`  ${rows.length} secureframe controls`);
console.log(`  ${soc2Refs.size} SOC 2 refs, ${cisRefs.size} CIS IG1 refs`);
console.log(`  ${seen.size} crosswalks`);
